server:
  port: 8081
  
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/    
      

spring:
  application:
    name: User


# PostgreSQL Database Connection Configuration

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: vfire
    driver-class-name: org.postgresql.Driver

# Hibernate JPA Configuration

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
      
      
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

 